group 'flutter.overlay.window.flutter_overlay_window'
version '1.0'

plugins {
    id 'com.android.library'
}

repositories {
    google()
    mavenCentral()
}

android {
    namespace 'flutter.overlay.window.flutter_overlay_window'

    compileSdk 35

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdkVersion 21
    }
}